//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Contact
{
    public int ContactKey { get; set; }
    public string ContactNumber { get; set; }
    public Nullable<int> ContactTypeKey { get; set; }
    public Nullable<int> PersonKey { get; set; }

    public virtual Person Person { get; set; }
}

public partial class GrantRequest
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public GrantRequest()
    {
        this.GrantReviews = new HashSet<GrantReview>();
    }

    public int GrantRequestKey { get; set; }
    public System.DateTime GrantRequestDate { get; set; }
    public Nullable<int> PersonKey { get; set; }
    public Nullable<int> GrantTypeKey { get; set; }
    public string GrantRequestExplanation { get; set; }
    public Nullable<decimal> GrantRequestAmount { get; set; }

    public virtual GrantType GrantType { get; set; }
    public virtual Person Person { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<GrantReview> GrantReviews { get; set; }
}

public partial class GrantReview
{
    public int GrantReviewKey { get; set; }
    public System.DateTime GrantReviewDate { get; set; }
    public Nullable<int> GrantRequestKey { get; set; }
    public string GrantRequestStatus { get; set; }
    public Nullable<decimal> GrantAllocationAmount { get; set; }
    public Nullable<int> EmployeeKey { get; set; }

    public virtual GrantRequest GrantRequest { get; set; }
}

public partial class GrantType
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public GrantType()
    {
        this.GrantRequests = new HashSet<GrantRequest>();
    }

    public int GrantTypeKey { get; set; }
    public string GrantTypeName { get; set; }
    public decimal GrantTypeMaximum { get; set; }
    public decimal GrantTypeLifetimeMaximum { get; set; }
    public string GrantTypeDescription { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<GrantRequest> GrantRequests { get; set; }
}

public partial class LoginHistoryTable
{
    public int LoginHistoryKey { get; set; }
    public Nullable<int> PersonKey { get; set; }
    public System.DateTime LoginTimeStamp { get; set; }

    public virtual Person Person { get; set; }
}

public partial class Person
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Person()
    {
        this.Contacts = new HashSet<Contact>();
        this.GrantRequests = new HashSet<GrantRequest>();
        this.LoginHistoryTables = new HashSet<LoginHistoryTable>();
        this.PersonAddresses = new HashSet<PersonAddress>();
    }

    public int PersonKey { get; set; }
    public string PersonLastName { get; set; }
    public string PersonFirstName { get; set; }
    public string PersonEmail { get; set; }
    public byte[] PersonPassWord { get; set; }
    public System.DateTime PersonEntryDate { get; set; }
    public Nullable<int> PersonPassWordSeed { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Contact> Contacts { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<GrantRequest> GrantRequests { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<LoginHistoryTable> LoginHistoryTables { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PersonAddress> PersonAddresses { get; set; }
}

public partial class PersonAddress
{
    public int PersonAddressKey { get; set; }
    public string PersonAddressApt { get; set; }
    public string PersonAddressStreet { get; set; }
    public string PersonAddressCity { get; set; }
    public string PersonAddressState { get; set; }
    public string PersonAddressZip { get; set; }
    public Nullable<int> PersonKey { get; set; }

    public virtual Person Person { get; set; }
}
